### ISSUE TITLE
I get this error messege when testing

### ISSUE THREAD

**Issue by marcusmiles1973** [bklavet/Echo-skill-to-control-Directv#69] opened 2018-01-13 15:40 UTC
The remote endpoint could not be called, or the response it returned was invalid.﻿  I follow the tutorial to the T and still get this message, please help B Money...

**Comment by vmweaver** [comment] 2018-01-13 16:17
Did you chck through all of the things in this post? https://github.com/bklavet/Echo-skill-to-control-Directv/issues/12

It will be important to make sure that you can control thing from your local network, then from your external address first.  This will ensure your DTV box is setup properly and that you have your router/firewall configured to forward traffic to your DTV box.

**Comment by marcusmiles1973** [comment] 2018-01-13 16:58
Ok.  I got it to pause inside the network but no success on the outside.  The port is forwarded to 8080 so I don't understand.  Im sorry, im a noob when it comes to this. I have a plex server setup and forwarded to port 32400 so I know that the router is working.

**Comment by vmweaver** [comment] 2018-01-13 17:19
I assume the configuration is the same between your Plex port forwarding as with the DTV port forwarding?  Did you have to configure any type of Firewall Rule to allow Plex inbound? 
What type of router/FW are you running?  
Is your external IP address IPv4 (xxx.xxx.xxx.xxx) or IPv6 (XXXX::XXXX:XXXX:XXXX:XXXX) or both?
Please note to NOT include your actual address in any post!

**Comment by marcusmiles1973** [comment] 2018-01-13 17:31
the router is a comcast gateway smcd3gny.  security type: TCP. my public ip is [removed IPv6 Address].  no special firewall settings

**Comment by vmweaver** [comment] 2018-01-13 17:40
Since this is an IPv6 address, you may have to specify the destination as 
http://[IPv6Address]:8080/tv/getTuned (note the square brackets enclosing the address) 
Is this the format you are using to test externally?

**Comment by marcusmiles1973** [comment] 2018-01-13 17:41
yes it is but i delete the brackets.

**Comment by marcusmiles1973** [comment] 2018-01-13 17:52
this is what i paste inside of the browser. http://IPv6Address:8080/remote/processkey?key=pause&hold=keypress.  Then is sends me to the did you mean page.

**Comment by vmweaver** [comment] 2018-01-13 17:58
Any difference by including the bracket around the address?

**Comment by marcusmiles1973** [comment] 2018-01-13 17:59
No, no difference at all

**Comment by vmweaver** [comment] 2018-01-13 18:06
And hitting your Plex server using your external address works fine in your browser?
Is the URL somethign like "http://Ipv6Address:32400/web" ??
Sorry for all the questions on this.. just trying to determine where the issue lies.

**Comment by marcusmiles1973** [comment] 2018-01-13 18:15
Well I just tried that and it didn't work either.  I usually just go to my
app on my phone,or tablet to access it.

**Comment by bklavet** [comment] 2018-01-13 18:18
is there a dmz option to put your dtv local ip into?  this would help confirm if it is a router/isp blocking issue.

**Comment by marcusmiles1973** [comment] 2018-01-13 18:26
Yes there is but I don't know how to set it up

**Comment by bklavet** [comment] 2018-01-13 18:33
Google search how to set up [your router make/model] for dmz on Comcast.  you may be able to find something that helps show the setup.   DMZ for mine is just a matter of enabling it, and assigning a local ip address.  It throws that ip in front of its firewall.  the Ip you will want to use is the local ip assigned to the dtv receiver.

**Comment by marcusmiles1973** [comment] 2018-01-13 18:36
Ok I just enabled it and put in my receivers up address.

**Comment by bklavet** [comment] 2018-01-13 18:37
http://ipv6address:8080/remote/processkey?key=pause&hold=keypress

try this one again and see if it works,

**Comment by marcusmiles1973** [comment] 2018-01-13 18:47
It's a no go.  Same thing  it goes directly to a search results page

**Comment by bklavet** [comment] 2018-01-13 18:57
not looking good,
double check port 8080 here.
http://canyouseeme.org/

**Comment by marcusmiles1973** [comment] 2018-01-13 18:58
This is how I can access my plex.  [ipv4]:32400/web

**Comment by bklavet** [comment] 2018-01-13 19:00
its open
well it looks open....
I checked it against this site aswell
https://networkappers.com/tools/open-port-checker

step one in issue 12 has been confirmed right?  you have it set up to allow third parties.
somethings not right, the port looks open.  you should be able to control it.

**Comment by marcusmiles1973** [comment] 2018-01-13 19:02
Ok did a check and came back with a can't see error

**Comment by marcusmiles1973** [comment] 2018-01-13 19:14
Ok, just found,out that my port 80 and 8080 is, reserved for smc.  Is there
a way to use any other ports?

On Jan 13, 2018 2:02 PM, "Marcus Miles" <marcusmiles.1973@gmail.com> wrote:

Ok did a check and came back with a can't see error

**Comment by vmweaver** [comment] 2018-01-13 19:16
so.. a few things:
1. This an ipv4 address, so that's a bit easier.
2. You should be able to configure your portforwarding to use (say) port 3000 to 3000 (range) and then direct it to port 8080 on the DTV box.

**Comment by marcusmiles1973** [comment] 2018-01-13 19:20
Ok.  If you can,give me some instruction on how to redirect to dvr, I will
configure the router then take a break.  I really appreciate you working
with me.

**Comment by marcusmiles1973** [comment] 2018-01-13 19:31
I was using the port checker on my cellphone with the Wi-Fi off.  With the
Wi-Fi on, it says port 8080 is open.

On Jan 13, 2018 2:20 PM, "Marcus Miles" <marcusmiles.1973@gmail.com> wrote:

Ok.  If you can,give me some instruction on how to redirect to dvr, I will
configure the router then take a break.  I really appreciate you working
with me.

**Comment by vmweaver** [comment] 2018-01-13 19:38
Sure..  
1. First thing would be to undo the DMZ configuration
2. Now go to the Port Forwarding Configuration screen and item that you currently have setup for Port  8080
3. It will probably say something like "Starting Port" and "Ending Port"? If so, put those both as 3000

I am not sure where in the interface you tell it which "service" to use.  I think that is under a drop down for "common Services".. There may be a section that is for "other" service which will let you specify a port. If there is one, then put in 8080 and make sure the serverIP is that of your DTV box.

Does any of this line up with what you see in the UI?

**Comment by vmweaver** [comment] 2018-01-13 19:41
Does the UI look like this? 
![image](https://user-images.githubusercontent.com/2661181/34909476-7f64049c-f867-11e7-93b1-a4d7c0c26f11.png)

If so: LAN Server IP = DTV IP address
         Remote IPs: ANY
         Public IP Ports: Single
         Start Public Port: 3000
         End Public Port: 3000 (if you have to put something in)
         Private Port: 8080

**Comment by vmweaver** [comment] 2018-01-15 23:25
@marcusmiles1973 Any luck with these settings or can you provide additional info?

**Comment by marcusmiles1973** [comment] 2018-01-15 23:28
No luck.  I have to take a snapshot of my gui settings but I have to reset
my router each time I want to log into it so I'll do that and send to you
in a few.

**Comment by vmweaver** [comment] 2018-01-16 00:35
Yikes, you have to reset it to login? Why is that?

**Comment by marcusmiles1973** [comment] 2018-01-16 01:43
I tried sending a pic of my interface but it won't go through.  Do you have
another email?  Not sure,why my router makes me do that but on deck log
out, I try to log back in and all it does is search then goes to the page
not found.

On Jan 15, 2018 7:35 PM, "mawrew19" <notifications@github.com> wrote:

Yikes, yo have to reset it to login? Why is that?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bklavet/Echo-skill-to-control-Directv/issues/69#issuecomment-357820253>,
or mute the thread

**Comment by vmweaver** [comment] 2018-01-16 02:00
Sure.   [email redacted]

**Comment by marcusmiles1973** [comment] 2018-01-16 02:14
It says that email can't be found.  [email redacted]

**Comment by vmweaver** [comment] 2018-01-20 18:35
@marcusmiles1973 
Was great working with you just now and glad we got this worked out for you.
For documentation purposes:  
I believe your original router would NOT allow a port forward for 8080, nor would it allow you to "port translate" from say "3000 externally to 8080 internally".  Good work to replace that router with one that could actually work! ;-)

You had everything fine, but had gone into the realm of Publishing the skill. I am not sure if that caused issues or not.  I recall you ALSO had "Skill Verification" enabled.  I don't have mine setup that way, so I undid that too.  I will play with both of those settings to see what was truly the cause of your issues.

Have fun playing!

**Closed as completed by vmweaver** 2018-01-20 18:35 UTC

**Comment by marcusmiles1973** [comment] 2018-01-23 23:39
Hey hows it going man?  I have a question, there are a few channels missing
inside of the custom slot values like WUPA.  Do I just type it in and
upload it or is there something else that I need to do to activate it?

**Comment by bklavet** [comment] 2018-01-23 23:44
what channel is WUPA?

**Comment by bklavet** [comment] 2018-01-23 23:47
is this wupa in atlanta channel 69?

**Comment by marcusmiles1973** [comment] 2018-01-24 00:00
Yes it is

**Comment by bklavet** [comment] 2018-01-24 00:45
so do me a favor turn the main genie to WUPA and then put this in the browser enter, and then copy and paste the response here and I will show you how to add the channel.
http://[dtv ip]:8080/tv/getTuned

**Comment by marcusmiles1973** [comment] 2018-01-24 00:53
{
  "callsign": "WUPA",
  "date": "20180123",
  "duration": 1800,
  "isOffAir": false,
  "isPclocked": 3,
  "isPpv": false,
  "isRecording": false,
  "isVod": false,
  "major": 69,
  "minor": 65535,
  "offset": 1338,
  "programId": "74384096",
  "rating": "TV-PG",
  "startTime": 1516753800,
  "stationId": 3223472,
  "status": {
    "code": 200,
    "commandResult": 0,
    "msg": "OK.",
    "query": "/tv/getTuned"
  },
  "title": "Family Feud"
}

**Comment by bklavet** [comment] 2018-01-24 01:05
you will want to add something like this to the index

case "WUPA":
case "w.u.p.a..":
case "wupa":
	path = '/tv/tune?major=69';
                
	break;

you will want to add it after a "break;" and before another "case"

then go to the developer portal and add w.u.p.a. to the custom slot values.

odds are WUPA will go to lambda as w.u.p.u.  but i added the other case arguments on the chance alexa sends off WUPA or wupa.
if alexa sends something like "whoopa"  you may have to adjust accordingly.  

give it a shot and see how it goes

**Comment by marcusmiles1973** [comment] 2018-01-24 01:28
ok i wrote it into the index file now do you mean upload it to the
developers site?

**Comment by bklavet** [comment] 2018-01-24 01:52
you will want to zip your index with the alexa file, (like you did hte first time) and upload to lambda.  then go to the developer portal and add w.u.p.a. to the custom slot value, and then you can test it out.

**Comment by vmweaver** [comment] 2018-01-24 01:52
Yes.. so you will update the index file, zip it up with the Alexa file and upload that to the Lambda developer site.

Then you will go to the Alexa Skill and edit the "Control_List" custom slot type.  You should see other channels at the bottom of that list.  Just add the "w.u.p.a" to that list and save  it.

**Comment by vmweaver** [comment] 2018-01-24 02:14
for the index file, you will a bunch of entries like this:
                              case "ABC":
					path = '/tv/tune?major=397';
				break;
				
				case "amc":
					path = '/tv/tune?major=254';
				break;
case "WUPA":
case "w.u.p.a..":
case "wupa":
path = '/tv/tune?major=69';

break;
