### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by wwwgizy** [bklavet/Echo-skill-to-control-Directv#50] opened 2017-08-28 03:00 UTC
Error: There was a problem with your request: Unknown slot type 'Control_List' for slot 'Control'

**Comment by bklavet** [comment] 2017-08-28 03:12
the problem is going to be on the Interaction Model tab in the Amazon Developer Console.  when you get "Error: There was a problem with your request: Unknown slot type 'Control_List' for slot 'Control' this means that the Control_List entered in the custom slot Type does not match the Control_List in the schema.  you may have a space somewhere that you got with the pasting, but that is where your problem lies.  Thanks﻿

**Comment by wwwgizy** [comment] 2017-08-28 23:48
Can you help me with team viewer?

**Comment by vmweaver** [comment] 2018-01-09 22:43
@wwwgizy I know this is an old issue, but did you get it resolved?

**Comment by vmweaver** [comment] 2018-01-20 18:48
Closing issue

**Closed as completed by vmweaver** 2018-01-20 18:48 UTC
